export PATH='/usr/local/sbin:/var/jb/usr/local/sbin:/usr/local/bin:/var/jb/usr/local/bin:/usr/sbin:/var/jb/usr/sbin:/usr/bin:/var/jb/usr/bin:/sbin:/var/jb/sbin:/bin:/var/jb/bin:/usr/bin/X11:/var/jb/usr/bin/X11:/usr/games:/var/jb/usr/games'
export TMPDIR='/var/jb/tmp'
export PS1='%m%::%~ %n%# '	
umask 022

export EDITOR=/var/jb/usr/bin/editor
export PAGER=/var/jb/usr/bin/pager

for i in /var/jb/etc/profile.d/*.sh ; do
    if [ -r "$i" ]; then
        . $i
    fi
done
