TARGET := iphone:clang:latest:latest

include $(THEOS)/makefiles/common.mk

TOOL_NAME = HelloWorld

HelloWorld_FILES = main.m
HelloWorld_CFLAGS = -fobjc-arc
HelloWorld_INSTALL_PATH = /usr/local/bin

include $(THEOS_MAKE_PATH)/tool.mk
