TARGET := iphone:clang:latest:latest

include $(THEOS)/makefiles/common.mk

TOOL_NAME = Jupiter

Jupiter_FILES = main.m
Jupiter_CFLAGS = -fobjc-arc
Jupiter_INSTALL_PATH = /usr/local/bin

include $(THEOS_MAKE_PATH)/tool.mk
